#!/usr/bin/env bash
# Generate docs/rtm.md from `// REQ: ...` comments in tests.
# v0.1 stub. Replace with a real generator that scans `cargo test --list`.
set -euo pipefail

OUT="docs/rtm.md"
{
  echo "# Requirements Traceability Matrix (RTM)"
  echo ""
  echo "_Generated by \`scripts/gen-rtm.sh\` -- do not edit by hand._"
  echo ""
  echo "| Requirement | Tests | Status |"
  echo "| ----------- | ----- | ------ |"
  grep -RhoE '// REQ: [A-Z]+-[A-Za-z0-9_-]+' crates/ tests/ web/ 2>/dev/null \
    | sort -u \
    | awk '{ sub("// REQ: ", "", $0); print "| " $0 " | (auto) | covered |" }' \
    || true
} > "$OUT"
echo "Wrote $OUT"
