# Generate docs/rtm.md from `// REQ: ...` comments in tests.
# Windows equivalent of scripts/gen-rtm.sh. v0.1 stub.
$ErrorActionPreference = 'Stop'

$out = 'docs/rtm.md'
$searchDirs = @('crates', 'tests', 'web', 'scripts') | Where-Object { Test-Path $_ }

$ids = $searchDirs | ForEach-Object {
    Get-ChildItem -Recurse -Path $_ -Include *.rs, *.ts, *.tsx, *.ps1, *.sh -File -ErrorAction SilentlyContinue
} | ForEach-Object {
    Select-String -Path $_.FullName -Pattern '(?://|#) REQ: ([A-Z]+-[A-Za-z0-9_-]+)' -AllMatches
} | ForEach-Object {
    $_.Matches | ForEach-Object { $_.Groups[1].Value }
} | Sort-Object -Unique

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('# Requirements Traceability Matrix (RTM)')
$lines.Add('')
$lines.Add('_Generated by `scripts/gen-rtm.ps1` -- do not edit by hand._')
$lines.Add('')
$lines.Add('| Requirement | Tests | Status |')
$lines.Add('| ----------- | ----- | ------ |')
foreach ($id in $ids) {
    $lines.Add("| $id | (auto) | covered |")
}

$fullOut = Join-Path (Get-Location) $out
[System.IO.File]::WriteAllLines($fullOut, $lines, [System.Text.UTF8Encoding]::new($false))
Write-Host "Wrote $out"
