#!/usr/bin/env bash
# Generate docs/rtm.md from `// REQ: ...` comments in test/source files.
# Distinguishes implementation references from test evidence.
# Fails when a referenced requirement id is not declared in docs/requirements.md.
set -euo pipefail

OUT="docs/rtm.md"
python3 - "$OUT" <<'PY'
from __future__ import annotations

from collections import defaultdict
from pathlib import Path
import re
import sys

out = Path(sys.argv[1])
requirements = Path("docs/requirements.md")
req_pattern = re.compile(r"(?://|#)\s*REQ:\s*([A-Z]+-[A-Za-z0-9_-]+)")
heading_pattern = re.compile(r"^###\s+([A-Z]+-[A-Za-z0-9_-]+)\b", re.MULTILINE)
suffixes = {".rs", ".ts", ".tsx", ".ps1", ".sh"}
search_dirs = [Path(p) for p in ("crates", "tests", "web", "scripts") if Path(p).exists()]
skip_dirs = {"node_modules", "dist", ".vite"}

defined_order = heading_pattern.findall(requirements.read_text(encoding="utf-8"))
defined = set(defined_order)
impl_refs: dict[str, list[str]] = defaultdict(list)
test_refs: dict[str, list[str]] = defaultdict(list)


def is_test_path(path: Path) -> bool:
  rel = path.as_posix()
  return (
    rel.startswith("tests/")
    or "/tests/" in rel
    or rel.endswith((".test.ts", ".test.tsx", ".spec.ts", ".spec.tsx"))
  )


def rust_test_context_by_line(lines: list[str]) -> set[int]:
  test_lines: set[int] = set()
  brace_depth = 0
  pending_cfg_test = False
  test_depth: int | None = None

  for line_no, line in enumerate(lines, 1):
    if test_depth is not None:
      test_lines.add(line_no)

    stripped = line.strip()
    if re.search(r"#\s*\[\s*cfg\s*\(\s*test\s*\)\s*\]", line):
      pending_cfg_test = True
    if pending_cfg_test and re.search(r"\bmod\s+tests\b", line) and "{" in line:
      test_depth = brace_depth + 1
      pending_cfg_test = False

    brace_depth += line.count("{")
    brace_depth -= line.count("}")
    if test_depth is not None and brace_depth < test_depth:
      test_depth = None
    if (
      pending_cfg_test
      and stripped
      and not stripped.startswith("#[")
      and not re.search(r"\bmod\s+tests\b", line)
    ):
      pending_cfg_test = False

  return test_lines

for root in search_dirs:
  for path in sorted(
      p for p in root.rglob("*")
      if p.is_file() and p.suffix in suffixes and not any(part in skip_dirs for part in p.parts)
  ):
    try:
      text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError as exc:
      raise SystemExit(f"{path}: not valid UTF-8: {exc}") from exc
    rel = path.as_posix()
    lines = text.splitlines()
    path_is_test = is_test_path(path)
    rust_test_lines = rust_test_context_by_line(lines) if path.suffix == ".rs" else set()
    for line_no, line in enumerate(lines, 1):
      for match in req_pattern.finditer(line):
        req_id = match.group(1)
        target = test_refs if path_is_test or line_no in rust_test_lines else impl_refs
        target[req_id].append(f"{rel}:{line_no}")

referenced = set(impl_refs) | set(test_refs)
unknown = sorted(req_id for req_id in referenced if req_id not in defined)
if unknown:
  print("Unknown requirement id(s) referenced: " + ", ".join(unknown), file=sys.stderr)
  sys.exit(1)

lines = [
  "# Requirements Traceability Matrix (RTM)",
  "",
  "_Generated by `scripts/gen-rtm.*` -- do not edit by hand._",
  "",
  "| Requirement | Implementation references | Test evidence | Status |",
  "| ----------- | ------------------------- | ------------- | ------ |",
]
for req_id in defined_order:
  impl = "<br>".join(sorted(set(impl_refs.get(req_id, [])))) or "(none)"
  tests = "<br>".join(sorted(set(test_refs.get(req_id, [])))) or "(none)"
  if test_refs.get(req_id):
    status = "covered"
  elif impl_refs.get(req_id):
    status = "implementation-only"
  else:
    status = "unreferenced"
  lines.append(f"| {req_id} | {impl} | {tests} | {status} |")

out.write_text("\n".join(lines) + "\n", encoding="utf-8")
PY
echo "Wrote $OUT"
